ARG BUILDTAG=build
FROM kube-service-selectors:${BUILDTAG}
LABEL org.opencontainers.image.authors="Greenshift <contact@greenshift.app>"

COPY .coveragerc ./
COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-cache --extra dev

COPY tests ./tests
